### PR TITLE
#85 Hotfix/`RobertaTokenizerFast` object has no attribute `max_len`

### PR DESCRIPTION
**Pull request by kirzharov**
Link to the issue: #85

### CODE REVIEW

**Comment by kirzharov** [comment]
I checked `score` function locally and get results for precision, recall, and F1 measure with `transformers` versions:
* `4.0.0`
* `3.5.1`
* `2.8.0`

Looks like everything works as before for `transformers` version `4.0.0`

**Comment by felixgwu** [comment]
Hi @kirzharov 
Thank you for this pull request. I've verified that old versions work as before. However, it doesn't pass our test with transformers 4.0.0. It's possible that some other arguments have to be changed as well.

**Comment by kirzharov** [comment]
Hi @felixgwu, thanks! Did you mean about only `score` function or others?  I'll check 👍

**Comment by felixgwu** [comment]
When I ran `python -m unittest discover`, almost all the tests failed. It might be that they changed some default settings and the embeddings changed, but I haven't looked into the details.

**Comment by kirzharov** [comment]
@felixgwu Ok, thanks! I'll check today 👍

**Comment by felixgwu** [comment]
Hi @kirzharov, we have fixed the bug and merged your PR. FYI, the mismatch comes from the fact that huggingface's fast tokenizers are inconsistent with the old tokenizers and create different tokens. We disable the fast tokenizers currently. Thanks again for your help!

**Comment by kirzharov** [comment]
@felixgwu, awesome, thanks! It's great that you managed to fix this quickly. 🔥 I also noticed difference with new Fast tokenizers and `use_fast=False` 👍

**Comment by kalyankumarp** [comment]
Hi,
Do I have to wait for the 0.3.7 version of bert score to be able to use transformers 4.0.0? I tried 0.3.6 bert score with 4.0.0 transformers. I am still getting the same error.

Thanks,
Kalyan.

**Comment by felixgwu** [comment]
Hi @kalyankumarp, 
We have released veresion 0.3.7. Can you please share the error messages if it still doesn't work?

**Comment by kalyankumarp** [comment]
Hi Felix,

It's working. Thanks for the fix.

**Pull request merged**
