### PR TITLE
Precompute bert matrix embeddings

### PR DESCRIPTION
**Pull request by williamabrwolf**

### CODE REVIEW

**Comment by williamabrwolf** [comment]
Closed the other PR; this PR contains, additionally, the memoization code.

@Tiiiger please let me know what you might like to see pulled out into functions.

Also, the next thing to add is a precomputed `idf_dict`.

**Comment by Tiiiger** [comment]
@williamabrwolf I'll look into this and try to test this. Revert soon.

**Comment by williamabrwolf** [comment]
Revert soon?

**Comment by Tiiiger** [comment]
@williamabrwolf revert soon turns out to be two weeks... 

looks good to me overall. Can you provide some example code? it would be nice if you can use the [example input](https://github.com/Tiiiger/bert_score/tree/master/example). I will test the example code you give me and merge it afterward.

**Pull request closed without merging**
